FoodCleanB/Controllers/AboutController.cs
using System.Web.Mvc;

namespace FoodCleanB.Controllers
{
    public class AboutController : BaseController
    {
        [Route("lien-he.html")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

FoodCleanB/Controllers/AdminController.cs
using FoodCleanB.Database;
using FoodCleanB.Helpers;
using System;
using System.Linq;
using System.Web.Mvc;

namespace FoodCleanB.Controllers
{
    [Login]
    [Admin]
    public class AdminController : BaseController
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        #region Nhóm hàng hóa

        [HttpGet]
        public ActionResult NhomHang()
        {
            var nhoms = Db.NhomHang.ToList();
            return View(nhoms);
        }

        [HttpGet]
        public ActionResult ThemNhomHang()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemNhomHang(NhomHang m)
        {
            if (m.Ten == null || m.Ten.Trim().Length == 0)
            {
                ModelState.AddModelError("Ten", "Tên nhóm bị bỏ trống.");
                return View(m);
            }

            if (Db.NhomHang.Any(o => o.Ten == m.Ten))
            {
                ModelState.AddModelError("Ten", "Nhóm này đã tồn tại.");
                return View(m);
            }

            Db.NhomHang.Add(m);
            Db.SaveChanges();
            TempData["Message"] = $"Thêm thành công {m.Ten}";

            return RedirectToAction("NhomHang");
        }

        #endregion Nhóm hàng hóa

        #region Sản phẩm

        [HttpGet]
        public ActionResult SanPham()
        {
            var list = Db.SanPham.OrderByDescending( x => x.MaHang).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult ThemSanPham()
        {
            ViewBag.NhaCungCap = Db.NhaCungCap.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
            ViewBag.NhomHang = Db.NhomHang.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();

            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemSanPham(SanPham m)
        {
            if (m?.TenHang == null || m.TenHang.Trim().Length == 0)
            {
                ModelState.AddModelError("TenHang", "Tên sản phẩm bị bỏ trống.");
            }

            if (m == null || !ModelState.IsValid)
            {
                ViewBag.NhaCungCap = Db.NhaCungCap.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
                ViewBag.NhomHang = Db.NhomHang.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();

                return View(m);
            }

            try
            {
                m.Sku = Guid.NewGuid();
                m.TenHang = m.TenHang?.Trim();

                Db.SanPham.Add(m);
                Db.SaveChanges();

                TempData["Message"] = $"Thêm thành công {m.MaHang}";

                return RedirectToAction("SanPham");
            }
            catch (Exception ex)
            {
                TempData["Message"] = (ex.InnerException ?? ex).Message;

                return RedirectToAction("SanPham");
            }
        }
		[HttpGet]
        // GET: Admin/Edit/5
        public ActionResult EditSanPham(int maHang)
        {
            ViewBag.NhaCungCap = Db.NhaCungCap.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
            ViewBag.NhomHang = Db.NhomHang.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
            var item = Db.SanPham.FirstOrDefault(o => o.MaHang == maHang);

            if (item == null)
            {
                TempData["Message"] = $"Không có sản phẩm với mã số {maHang}";

                return RedirectToAction("SanPham");
            }

            return View(item);
        }

        [HttpPost, ValidateInput(false)]
        
        public ActionResult EditSanPham(SanPham m)
        {
            if (m?.TenHang == null || m.TenHang.Trim().Length == 0)
            {
                ModelState.AddModelError("TenHang", "Tên sản phẩm bị bỏ trống.");
            }

            if (m == null || !ModelState.IsValid)
            {
                ViewBag.NhaCungCap = Db.NhaCungCap.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
                ViewBag.NhomHang = Db.NhomHang.Select(o => new SelectListItem { Value = o.MaSo.ToString(), Text = o.Ten }).ToList();
                return View(m);
            }

            try
            {
                // Tìm sản phẩm
                SanPham existed = Db.SanPham.FirstOrDefault(o => o.MaHang == m.MaHang);
                if (existed == null)
                {
                    TempData["Message"] = $"Không có sản phẩm với mã số {m.MaHang}";

                    return RedirectToAction("SanPham");
                }

                existed.TenHang = m.TenHang?.Trim();
                existed.AnhSanPham = m.AnhSanPham;
                existed.MaNhaCungCap = m.MaNhaCungCap;
                existed.MaNhomHang = m.MaNhomHang;
                existed.GiaThanh = m.GiaThanh;
                existed.KhoiLuong = m.KhoiLuong;
                existed.MoTa = m.MoTa;
                existed.KhuyenMai = m.KhuyenMai;
                existed.SoLuong = m.SoLuong;
                existed.TheTich = m.TheTich;

                Db.SaveChanges();
                TempData["Message"] = $"Cập nhật xong mã số {m.MaHang}";

                return RedirectToAction("SanPham");
            }
            catch (Exception ex)
            {
                TempData["Message"] = (ex.InnerException ?? ex).Message;

                return RedirectToAction("SanPham");
            }
        }

        // GET: Admin/Delete/5
        public ActionResult DeleteSanPham(int maHang)
        {
            // Tìm sản phẩm
            SanPham existed = Db.SanPham.FirstOrDefault(o => o.MaHang == maHang);

            if (existed == null)
            {
                TempData["Message"] = $"Không có sản phẩm với mã số {maHang}";

                return RedirectToAction("SanPham");
            }

            var card = Db.SanPhamGioHang.Where(o => o.MaHang == existed.MaHang);
            foreach (var sp in card)
            {
                Db.SanPhamGioHang.Remove(sp);
            }
            Db.SanPham.Remove(existed);
            Db.SaveChanges();

            TempData["Message"] = $"Đã xóa mã số {maHang}";

            return RedirectToAction("SanPham");
        }

        #endregion Sản phẩm

        [HttpGet]
        public ActionResult NhaCungCap()
        {
            var nhaCungCap = Db.NhaCungCap.ToList();
            return View(nhaCungCap);
        }

        [HttpGet]
        public ActionResult ThemNhaCungCap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemNhaCungCap(NhaCungCap m)
        {
            if (!ModelState.IsValid)
            {
                //
                return View(m);
            }

            m.MaSo = Guid.NewGuid();

            Db.NhaCungCap.Add(m);
            Db.SaveChanges();

            TempData["Message"] = $"Thêm thành công {m.Ten}";
            return RedirectToAction("NhaCungCap");
        }

        public ActionResult Coupon()
        {
            throw new NotImplementedException();
        }
    }
}

FoodCleanB/Views/Shared/LayoutLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/css/login.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Poppins">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            

            <!-- Icon -->
            <div class="fadeIn first">
                <img src="https://i.ya-webdesign.com/images/vegetables-icon-png-5.png" id="icon" alt="User Icon" />
            </div>

            @RenderBody()

            <div id="formFooter">
                <a href="@Url.Action("DangKy","Login")">Đăng ký</a> <br>
                <a class="underlineHover" href="#">Chuyên đề tốt nghiệp</a>
            </div>
        </div>
    </div>
</body>
</html>

FoodCleanB/Views/Shared/LayoutProfile.cshtml
@{
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}

<div class="profile">
    <div class="left-col">
        <ul class="nav-container">
            <li id="My-profile" class="nav-item">
                <a href="@Url.Action("UserProfile", "User")" data-spm="My-profile"><i class="fa fa-user"></i> Thông tin cá nhân</a>
            </li>
            <li id="Address-book" class="nav-item">
                <a href="@Url.Action("Shipping", "User")" data-spm="Address-book"><i class="fa fa-book"></i> Sổ địa chỉ</a>
            </li>
            <li id="Order" class="nav-item">
                <a href="@Url.Action("Order", "User")" data-spm="Orders"><i class="fa fa-people-carry"></i> Đơn hàng</a>
            </li>
            <li id="WishList" class="nav-item">
                <a href="@Url.Action("WishList", "User")"><i class="fa fa-heart"></i> Sản phẩm ưa thích</a>
            </li>
            <li id="WishList" class="nav-item">
                <a href="@Url.Action("ChangePassword", "User")"><i class="fa fa-key"></i> Đổi mật khẩu</a>
            </li>
        </ul>
    </div>
    <div class="right-col">
        @if (TempData["Message"] != null)
        {
            <h3 class="text-center font-weight-bold">@TempData["Message"]</h3>
        }

        @RenderBody()
    </div>
</div>

FoodCleanB/Views/Shared/LayoutShare.cshtml
@using FoodCleanB.Database

@{
    TaiKhoan user = Session["User"] as TaiKhoan;
}
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>Cửa hàng thực phẩm sạch - @ViewBag.Title</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <title> Thực phẩm sạch - Food clean </title>
    <script src="~/Scripts/home.js"></script>
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="~/images/apple-touch-icon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <!-- Site CSS -->
    <link rel="stylesheet" href="~/css/style.css">
    <link href="~/css/register.css" rel="stylesheet" />
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="~/css/responsive.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/custom.css">
    <!-- End copyright  -->
    <!-- ALL JS FILES -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <!-- ALL PLUGINS -->
    <script src="~/js/jquery.superslides.min.js"></script>
    <script src="~/js/bootstrap-select.js"></script>
    <script src="~/js/inewsticker.js"></script>
    <script src="~/js/bootsnav.js"></script>
    <script src="~/js/images-loded.min.js"></script>
    <script src="~/js/isotope.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/baguetteBox.min.js"></script>
    <script src="~/js/form-validator.min.js"></script>
    <script src="~/js/contact-form-script.js"></script>
    <script src="~/js/custom.js"></script>

    <script>
        $(document).on('click', '.add-card', function () {
            var itemId = $(this).data('itemid');

            $.ajax({
                method: 'POST',
                url: '@Url.Action("Insert", "Order")',
                data: { 'itemId': itemId },
                success: function(data) {
                    alert(data.Message);

                    if (data.Code == 1) {
                        var soSanPham = $('#cartCount').text();
                        console.log(soSanPham);
                        if (!soSanPham) {
                            soSanPham = 0;
                        }
                        soSanPham = parseInt(soSanPham);
                        soSanPham += 1;
                        $('#cartCount').text(soSanPham);
                    }
                }
            });
        });
    </script>
</head>
<body>

<!-- Start Main Top -->
<header class="main-header">
    <!-- Start Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-default bootsnav">
        <div class="container">
            <!-- Start Header Navigation -->
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")"><img src="~/images/logo.png" class="logo" alt="" width="100"></a>
            </div>
            <!-- End Header Navigation -->
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-menu">
                <ul class="nav navbar-nav ml-auto" data-in="fadeInDown" data-out="fadeOutUp">
                    <li class="nav-item active"><a class="nav-link" href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                    @*<li class="nav-item"><a class="nav-link" href="about.html">Về chúng tôi</a></li>*@
                    <li class="nav-item">
                        <a href="@Url.Action("List", "SanPham", new { Page = 1, Title ="tất-cả", Id = 0 })" class="nav-link">Cửa hàng</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="@Url.Action("Contact", "About")">Liên hệ</a></li>

                    @if (string.Equals(user?.TenDangNhap, "admin", StringComparison.InvariantCultureIgnoreCase))
                    {
                        <li class="nav-item"><a class="nav-link" href="@Url.Action("Index", "Admin")">Quản lý</a></li>
                    }

                    @if (user != null)
                    {
                        <li class="dropdown">
                            <a href="#" class="nav-link dropdown-toggle arrow" data-toggle="dropdown">Chào! @user.TenDangNhap</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="@Url.Action("UserProfile", "User")" class = "nav-link"><i class='fa fa-user'></i> Tài khoản</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Order", "User")" class = "nav-link"><i class='fa fa-people-carry'></i> Đơn hàng</a>
                                </li>
                                <li class="">
                                    <a href="@Url.Action("LogOut", "Login")" class = "nav-link"><i class='fa fa-door-open'></i> Đăng xuất</a>
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
            <!-- /.navbar-collapse -->
            <!-- Start Atribute Navigation -->
            <div class="attr-nav">
                <ul>
                    <li class="search">
                        <a href="#">
                            <i class="fa fa-search"></i>
                        </a>
                    </li>

                    @if (user != null && user.TenDangNhap != "admin")
                    {
                        @Html.Action("CartCount", "Order")
                    }

                    @if (user == null)
                    {
                        <li class="">
                            @Html.ActionLink("Đăng nhập", "Login", "Login")
                        </li>
                    }
                </ul>
            </div>
            <!-- End Atribute Navigation -->
        </div>
        <!-- Start Side Menu -->
        <!-- End Side Menu -->
    </nav>
    <!-- End Navigation -->
</header>
<!-- End Main Top -->
<!-- Start Top Search -->
<div class="top-search">
    <div class="container">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
            <input type="text" class="form-control" name="search" placeholder="Search" onkeypress="search(event,this.value)">
            <span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
        </div>
    </div>
</div>
<!-- End Top Search -->

<div class="content-food-clean container">
    @RenderBody()
</div>
<footer>
    <div class="footer-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-top-box">
                        <h3>Giờ mở cửa</h3>
                        <ul class="list-time">
                            <li>Thứ 2 - Thứ 6: 08.00am to 05.00pm</li>
                            <li>Thứ 7: 10.00am to 08.00pm</li>
                            <li>Chủ nhật: <span>Đóng cửa</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-top-box">
                        <h3>Bản tin</h3>
                        <form class="newsletter-box">
                            <div class="form-group">
                                <input class="" type="email" name="Email" placeholder="Email Address*" />
                                <i class="fa fa-envelope"></i>
                            </div>
                            <button class="btn hvr-hover" type="submit">Gửi</button>
                        </form>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-top-box">
                        <h3>Mạng xã hội</h3>
                        <p>Chia sẽ để quảng cáo.</p>
                        <ul>
                            <li><a href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-widget">
                        <h4>Giới thiệu về chúng tôi</h4>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-link">
                        <h4>Thông tin</h4>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Customer Service</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                            <li><a href="#">Terms &amp; Conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Delivery Information</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="footer-link-contact">
                        <h4>Liên hệ</h4>
                        <ul>
                            <li>
                                <p><i class="fas fa-map-marker-alt"></i>Địa chỉ: Michael I. Days 3756 <br>Preston Street Wichita,<br> KS 67213 </p>
                            </li>
                            <li>
                                <p><i class="fas fa-phone-square"></i>Số điện thoại: <a href="+84945935480">+84945935480</a></p>
                            </li>
                            <li>
                                <p><i class="fas fa-envelope"></i>Email: <a href="mailto:haha123@gmail.com">haha123@gmail.com</a></p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- End Footer  -->
<!-- Start copyright  -->
<div class="footer-copyright">
    <p class="footer-company">
        All Rights Reserved. &copy; 2020 <a href="#">ThewayShop</a> Design By : Our
        <a href="https://html.design/">html design</a>
    </p>
</div>
</body>
    <script>
        function search(event, keyword) {
            
            if (event.keyCode == 13) {
                
                window.location.href = '@Url.Action("Search","SanPham")?search=' + keyword;
            }
        }
    </script>
</html>

FoodCleanB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>