FoodCleanB/Controllers/SanPhamController.cs
using FoodCleanB.Database;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace FoodCleanB.Controllers
{
    public class SanPhamController : BaseController
    {
        public PartialViewResult HomeProduct(int? nhomHang)
        {
            IQueryable<SanPham> list;
            if (nhomHang != null)
            {
                list = Db.SanPham.Where(o => o.MaNhomHang == nhomHang);
            }
            else
            {
                list = Db.SanPham.Take(12);
            }

            return PartialView(list.ToList());
        }

        [Route("san-pham/{title}-{itemId}.html")]
        [HttpGet]
        public ActionResult Detail(int ItemId, string title)
        {
            var sanPham = Db.SanPham.FirstOrDefault(o => o.MaHang == ItemId);

            return View(sanPham);
        }
        
        [Route("nhom-hang/{title}-{id}-trang-{page}.html")]
        [HttpGet]
        public ActionResult List(int page = 1, int id = 0, string title = null)
        {
            const int pageSize = 12;

            ViewBag.NhomHang = id;
            ViewBag.NhomHangTen = title;
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;

            List<SanPham> lstSanPham = new List<SanPham>();
            if (id > 0)
            {
                var getNameCate = Db.NhomHang.FirstOrDefault(x => x.MaSo == id);
                if (getNameCate != null)
                {
                    ViewBag.Category = getNameCate.Ten;
                    ViewBag.Total = getNameCate.SanPham.Count();
                    
                    lstSanPham = getNameCate.SanPham.ToList();
                }
            }
            else
            {
                ViewBag.Total = Db.SanPham.Count();
                lstSanPham = Db.SanPham.ToList();
            }

            // Phân trang, [pageSize] sản phẩm mỗi trang
            return View(lstSanPham.Skip(pageSize * (page-1)).Take(pageSize).ToList());
        }

        public ActionResult Search(string search)
        {
            if (search != null)
            {
                var result = Db.SanPham.Where(x => x.TenHang.ToLower().Contains(search.ToLower())).ToList();
                
                return View("List", result);
            }

            return RedirectToAction("List");
        }
    }
}

FoodCleanB/Views/SanPham/Detail.cshtml
@model FoodCleanB.Database.SanPham

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}

<div class="nav">
    <a href="@Url.Action("List","SanPham", new { Page = 1, Id = Model.NhomHang.MaSo, Title = Model.NhomHang.Ten.ToLower().Replace(" ","-")})">@Model.NhomHang.Ten</a> / @Model.TenHang
</div>

<!-- Start Shop Detail  -->
<div class="shop-detail-box-main">
    <div class="container">
        <div class="row">
            <div class="col-xl-5 col-lg-5 col-md-6">
                <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel" >
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active"> <img class="d-block w-100 img-responsive img-thumbnail" src="@Model.AnhSanPham" alt="First slide"> </div>
                        
                    </div>
                </div>
            </div>
            <div class="col-xl-7 col-lg-7 col-md-6">
                <div class="single-product-details">
                    <h2>@Model.TenHang</h2>
                    <h5>
                        @if (Model.KhuyenMai != null)
                        {
                            <del>@Model.GiaThanh đ</del>
                            @Html.Raw((Model.GiaThanh - Model.KhuyenMai) + "đ")
                        }
                        else
                        {
                            @Html.Raw(Model.GiaThanh)
                        }

                    </h5>
                    <h4>Kho: @Model.SoLuong</h4>
                    <h4>Mô tả sản phẩm</h4>
                    <p>
                        @Html.Raw(Model.MoTa)
                    </p>

                    <div class="price-box-bar add-to-btn">
                        <div class="cart-and-bay-btn mb-2">
                            <a class="btn hvr-hover add-card" data-itemid="@Model.MaHang" href="#">
                                <i class="fas fa-cart-plus"></i> Thêm vào giỏ
                            </a>
                            <a class="btn hvr-hover" href="#" data-itemid="@Model.MaHang">
                                <i class="fas fa-heart"></i> Add to wishlist
                            </a>
                        </div>
                        <div class="share-bar">
                            <a class="btn hvr-hover" href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a>
                            <a class="btn hvr-hover" href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a>
                            <a class="btn hvr-hover" href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a>
                            <a class="btn hvr-hover" href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a>
                            <a class="btn hvr-hover" href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-12">
                <h4>Chi tiết:</h4>
                <p>
                    @Html.Raw(Model.MoTa)
                </p>
            </div>
        </div>

     
    </div>
</div>
<!-- End Cart -->

FoodCleanB/Views/SanPham/HomeProduct.cshtml
@model List<FoodCleanB.Database.SanPham>

@if (!Model.Any())
{
    <div class="col-12 text-center pt-3">
        Chưa có sản phẩm
    </div>
}
else
{
    foreach (var item in Model)
    {
        <div class="col-lg-3 col-md-6 special-grid best-seller">
            <div class="products-single fix">
                <div class="box-img-hover">
                    <div class="type-lb">
                        @if (item.KhuyenMai > 0)
                        {
                            <p class="sale">
                                <del>@item.GiaThanh.ToString("##,###") đ</del>
                            </p>
                        }

                    </div>
                    <div class="image-box">
                        <img src="@item.AnhSanPham" class="img-fluid img-responsive img-thumbnail" alt="Image">
                    </div>
                    
                    <div class="mask-icon">
                        <ul>
                            <li>
                                <a href="@Url.Action("Detail", new {ItemId = item.MaHang, Title = item.TenHang.Replace(" ", "-")})" data-toggle="tooltip" data-placement="right" title="View">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </li>
                            <li><a href="#" data-toggle="tooltip" data-placement="right" title="Lưu lại"><i class="far fa-heart"></i></a></li>
                        </ul>

                        <a class="cart add-card" href="#" data-itemid="@item.MaHang">Thêm vào giỏ</a>
                    </div>
                </div>
                <div class="why-text">
                    <h4><a href="@Url.Action("Detail","SanPham", new {ItemId = item.MaHang, Title = item.TenHang.ToLower().Replace(" ", "-")})" title="View">@item.TenHang</a></h4>

                    <h5 class="price">
                        @Html.Raw((item.GiaThanh - (item.KhuyenMai ?? 0)).ToString("##,###")) đ
                    </h5>
                </div>
            </div>
        </div>
    }

}

FoodCleanB/Views/SanPham/List.cshtml
@model List<FoodCleanB.Database.SanPham>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/LayoutShare.cshtml";

    var pageNumber = ViewBag.Page as int? ?? 1;
    var pageSize = ViewBag.PageSize as int? ?? Model.Count;
    var totalItem = ViewBag.Total as int? ?? pageSize;
    var totalPage = (int)Math.Ceiling((double)totalItem / pageSize);
}

<h2>Sản phẩm của cửa hàng</h2>
@if (ViewBag.Category != null)
{
    <h3>Loại: @ViewBag.Category</h3>
}

<div class="row">
    @Html.Partial("HomeProduct", Model)
</div>

@if (pageNumber <= totalPage)
{
    <div class="paging d-block text-center">
        @if (pageNumber > 1)
        {
            <a class="btn btn-link btn-prev" href="@Url.Action("List", new { Page = pageNumber - 1, Id = ViewBag.NhomHang, Title = ViewBag.NhomHangTen })"><i class="fa fa-chevron-left"></i> Trước</a>
        }

        <span class="btn page-number">@pageNumber</span>

        @if (pageNumber < totalPage)
        {
            <a class="btn btn-link btn-next" href="@Url.Action("List", new { Page = pageNumber + 1, Id = ViewBag.NhomHang, Title = ViewBag.NhomHangTen })">Tiếp <i class="fa fa-chevron-right"></i></a>
        }
    </div>
}